/// Flutter icons Aula3
/// Copyright (C) 2020 by original authors @ fluttericon.com, fontello.com
/// This font was generated by FlutterIcon.com, which is derived from Fontello.
///
/// To use this font, place it in your fonts/ directory and include the
/// following in your pubspec.yaml
///
/// flutter:
///   fonts:
///    - family:  Aula3
///      fonts:
///       - asset: fonts/Aula3.ttf
///
/// 
/// * Material Design Icons, Copyright (C) Google, Inc
///         Author:    Google
///         License:   Apache 2.0 (https://www.apache.org/licenses/LICENSE-2.0)
///         Homepage:  https://design.google.com/icons/
/// * Font Awesome, Copyright (C) 2016 by Dave Gandy
///         Author:    Dave Gandy
///         License:   SIL ()
///         Homepage:  http://fortawesome.github.com/Font-Awesome/
///
import 'package:flutter/widgets.dart';

class Aula3 {
  Aula3._();

  static const _kFontFam = 'Aula3';

  static const IconData android = IconData(0xe800, fontFamily: _kFontFam);
  static const IconData apple = IconData(0xf179, fontFamily: _kFontFam);
  static const IconData windows = IconData(0xf17a, fontFamily: _kFontFam);
}
